### ISSUE TITLE
property attribute

### ISSUE THREAD

**Issue by bhartzler** [toddreed/Touchpose#11]
I think you want "strong" on this property attribute, no? I'm getting a warning in xcode 5.1 with mixed arc/non-arc code.

@property (nonatomic, strong) UIImage *customTouchImage;

**Comment by jjxtra** [comment]
Yes, I agree. This needs a strong property.

**Comment by toddreed** [comment]
All properties of retainable object type now explicitly specify their ownership (`strong`, `weak`, ...), but no guarantee that this mixed ARC/non-ARC code will work. At this stage, hopefully everybody is 100% ARC.
