### ISSUE TITLE
Expressions are not allowed at the top level

### ISSUE THREAD

**Issue by codebeaulieu** [toddreed/Touchpose#17]
using swift 2 I'm getting the error: "Expressions are not allowed at the top level" in your sampleMain.swift file in Xcode 7.1 beta

I've included the import statement and all the necessary files.

**Comment by dnadan** [comment]
Seems to work if you have this in your main.swift:

```swift
import UIKit
import Touchpose

UIApplicationMain(Process.argc, Process.unsafeArgv, NSStringFromClass(QTouchposeApplication.self), NSStringFromClass(AppDelegate.self))
```

Then I wanted to always show touches, so in AppDelegate's didFinishLaunchingWithOptions:
```swift
if let touchposeApplication = application as? QTouchposeApplication {
   touchposeApplication.alwaysShowTouches = true
}
```

**Comment by toddreed** [comment]
The equivalent instructions for Swift 3 are now in the README file (currently on the `develop` branch).
